entity:
  gender: Female
  language: English
  name: Juno
  persona: null
  personality: Friendly
  prompt: You are a assistant designed to concisely help the user with their queries.
  role: Assistant
system:
  TTS: Azure
  gpt_model: ''
  package: virtual_assistant
  startup_sound: true
  voice_name: Jenny
  voice_recognition_engine: Azure
user:
  user_age: null
  user_gender: null
  user_name: null
