interaction:
  language: English
  personality: sassy
  prompt: you are a virtual assistant
  role: assistant
system:
  package: virtual_assistant
  startup_sound: true
  voice_engine: azure
  voice_name: Juno
  voice_recognition_engine: azure
user:
  gender: female
  name: Juno
