entity:
  gender: male
  language: english
  name: Juno
  persona: null
  personality: friendly
  prompt: you are an assistant designed to concisely help the user with their queries
  role: assistant
system:
  gpt_model: virtual-assistant
  package: virtual_assistant
  startup_sound: true
  tts: azure
  voice_name: jenny
  voice_recognition_engine: azure
user:
  user_gender: male
  user_name: null
