entity:
  name: Oswald
  gender: male
  language: english ## see documentation for available languages
  personality: friendly
  persona: null ## entity will act as if they are this persona 
  prompt: you are an assistant designed to concisely help the user with their queries ## prompt to be used by GPT
  role: assistant  
system:
  gpt_model: virtual-assistant
  package: virtual_assistant ## optional
  startup_sound: true ## optional
  tts: elevenlabs ## or azure
  voice_name: Oswald ## custom voice modeled after Obama, created using Elevenlabs.
  voice_recognition_engine: azure # currently only azure available
user:
  user_name: null  
  user_gender: male 