# 'azure': To use Azure Key Vault 
# 'environment': To use environment variables 
# 'local': To store locally in a yaml file
preferred_secret_storage: 'azure' # or 'environment' or 'local'

api_keys:
  # REQUIRED: an OpenAI API key is required
  openai: null
  # Optional: used for weather retrieval
  weathermap: null
  # Optional: used for text-to-speech (if not provided Azure is used)
  elevenlabs: null
  # The rest will be autimatically created and filled in
  key_vault_name: null
  region: null
  cognitive_services_api: null
  luis_app_id: null
  luis_key: null
  openai_key: null
  weather_key: null
  translator_key: null
  elevenlabs_api_key: null
  news_key: null
  spotify_client_id: null
  spotify_client_secret: null

