# 'azure': To use Azure Key Vault 
# 'environment': To use environment variables 
# 'local': To store locally in a yaml file
preferred_secret_storage: 'azure' # or 'environment' or 'local'

api_keys:
  # REQUIRED: In order to use GPT, an OpenAI API key is required
  openai: ''

  # Optional: used for weather retrieval
  weathermap: ''

  # Optional: used for text-to-speech (if not provided Azure is used)
  elevenlabs: ''

# Will auto fill if preferred_secret_storage = 'azure'
azure:
  key_vault_name: ''
  region: ''
  cognitive_services_api: ''
  luis_app_id: ''
  luis_key: ''
  openai_key: ''
  weather_key: ''
  translator_key: ''
  elevenlabs_api_key: ''

# Will auto fill if preferred_secret_storage = 'environment'
environment:
  region: ''
  cognitive_services_api: ''
  luis_app_id: ''
  luis_key: ''
  openai_key: ''
  weather_key: ''
  translator_key: ''
  elevenlabs_api_key: ''

# Will auto fill if preferred_secret_storage = 'local'
local:
  file_path: '/path/to/my/secrets/file'
