# 'azure': To use Azure Key Vault 
# 'environment': To use environment variables 
# 'local': To encrypt and store data locally to a yaml file (Recommended for speed)
preferred_secret_storage: 'local' 

# 'azure': To use Azure Speech Recognition
speech_recognition_engine: 'azure'

# 'azure': To use Azure Text-to-speech
# 'elevenlabs': To use Elevenlabs Text-to-speech
text_to_speech_engine: 'azure'

# Keyvault name and region used by Azure
KEYVAULT_NAME: Juno-vault
REGION: eastus

# Project and deployment name for your conversational language resource
CLU_PROJECT_NAME: Juno
CLU_TRAINING_MODEL_NAME:  Model1
CLU_DEPLOYMENT_NAME: Model1

# Below are the required and optional api keys with links to where to acquire them
# Replace 'null' with your api key value
# Example: OPENAI-API-KEY: 'sk-test9HJ84Havnf8Haf5Hakngi5Hgfn'
api_keys:

  # REQUIRED: used to interact with OpenAI's GPT model
  # https://help.openai.com/en/articles/4936850-where-do-i-find-my-secret-api-key
  OPENAI-API-KEY: null

  # Optional: used for weather retrieval
  # https://openweathermap.org/api
  WEATHER-API-KEY: null

  # Optional: used for text-to-speech (if not provided Azure is used)
  # https://docs.elevenlabs.io/welcome/introduction
  ELEVENLABS-API-KEY: null

  # Optional: used for news retrieval
  # https://newsapi.org/
  NEWS-API-KEY: null

  # Optional: used for playing music via Spotify
  # https://developer.spotify.com/documentation/web-api
  SPOTIFY-CLIENT-ID: null
  SPOTIFY-CLIENT-SECRET: null

  # These will automatically be updated once 'create_infrastructure.sh' is executed and the necessary cloud infra is built
  COGNITIVE-SERVICES-API-KEY: null
  TRANSLATOR-API-KEY: null
  CLU-API-KEY: null
  CLU-ENDPOINT: null
